import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import glob

from itertools import product

plt.rc("text", usetex=True)
plt.rc("font", family="serif")

# Read data
dfs = [pd.read_csv(filename) for filename in glob.iglob("table*")]
df = pd.concat(dfs)

epsilons = df["epsilon"].unique()
graphs = {}
for epsilon in epsilons:
    single_experiment = df.loc[df["epsilon"] == epsilon]
    #ys = np.log(single_experiment["achieved_sparsity"] / single_experiment["bound"])
    ys = np.log(single_experiment["num_formulas"])
    graphs[epsilon] = ys

# Graph Difference between sparsity bound and achieved sparsity
xs = [x for x in range(3, 16)]

fig, axs = plt.subplots(2,2)

colours = ['r', 'g', 'b', 'y']
for n, (i,j) in enumerate(product([0,1], repeat=2)):
    axs[i,j].plot(xs, graphs[epsilons[n]], colours[n])
    axs[i,j].set_title(r"$\epsilon = {}$".format(epsilons[n]))
    axs[i,j].set_xlabel(r"Number of variables $n$")
    axs[i,j].set_ylabel(r"Number of Formulas $F_i$")
fig.suptitle(r"Number of formulas generated by the sparsification for different $\epsilon$")
plt.show()
