import numpy as np
import matplotlib.style as mlpstyle
import matplotlib.pyplot as plt
import pandas as pd
import glob

from itertools import product

mlpstyle.use("ggplot")
plt.rc("text", usetex=True)
plt.rc("font", family="serif")


TABLE_NUM = 2

# Read data
dfs = [pd.read_csv(filename) for filename in glob.iglob("table*")]

# Graph Difference between sparsity bound and achieved sparsity
xs = [x for x in range(dfs[TABLE_NUM]["n"].min(), dfs[TABLE_NUM]["n"].max() + 1)]
ys1 = dfs[TABLE_NUM]["bound"]

fig, axs = plt.subplots()
axs.plot(xs, ys1, marker="o")
plt.title(r"Upper bound on sparsity generated with $\epsilon = {}$".format(20))
plt.xlabel(r"Variables $n$")
plt.ylabel(r"Sparsity")
plt.show()

# colours = ['r', 'g', 'b', 'y']
# for n, (i,j) in enumerate(product([0,1], repeat=2)):
#     axs[i,j].plot(xs, graphs[epsilons[n]], colours[n])
#     axs[i,j].set_title(r"$\epsilon = {}$".format(epsilons[n]))
#     axs[i,j].set_xlabel(r"Number of variables $n$")
#     axs[i,j].set_ylabel(r"Number of Formulas $F_i$")
# fig.suptitle(r"Number of formulas generated by the sparsification for different $\epsilon$")
